---
model:
  name: MagnifierNet
  parameters:
    num_classes: 1
    freeze_backbones: False
    channels: 12
  weights:
    big_net: weights/HF_mit_b0_12c.pth
    small_net: weights/HF_mit_b0_12c.pth

metrics:
  Accuracy: { num_classes: &num_classes 2 }
  Precision: { num_classes: *num_classes, average: none, mdmc_average: global }
  Recall: { num_classes: *num_classes, average: none, mdmc_average: global }
  F1Score: { num_classes: *num_classes, average: none, mdmc_average: global }
  JaccardIndex: { num_classes: *num_classes, reduction: none}

losses:
  classification:
    name: loss.AsymmetricUnifiedFocalLoss
    normalized_scores: true
    parameters:
      weight: 0.5
      delta: 0.6
      gamma: 0.1
  regression:
    name: MSELoss
    parameters: {}
  distance:
    name: HuberLoss
    parameters: {delta: 1.35}
  distance_loss_weight: 0.5

rgb_channels: [ 3, 2, 1 ]
classes: *num_classes
lr: 0.001

optimizer:
  name: AdamW
  parameters:
    weight_decay: 0.01

scheduler:
  name: StepLR
  parameters:
    step_size: 15