seed: 42

pre_available: False
mode: post
root: "../california_burned_areas"

train_set: null
test_set: ???

validity_filter: ["y"]
comments_filter: [6]

batch_size: 8
num_workers: 4

patch_size: 512
keep_burned_only: true
debug: false