seed: 42

pre_available: False
mode: post
root: "/data2/drege/magnifier-california/data/europe.hdf5"

train_set: null
test_set: coral

batch_size: 6
num_workers: 4

patch_size: 512
keep_burned_only: true
debug: false